### ISSUE TITLE
Update webln provider #enable() function to return void

### ISSUE THREAD

**Issue by bumi** [OneKeyHQ/cross-inpage-provider#124]
The webln spec defines the enable() function as void. It should not return any response.

https://www.webln.guide/building-lightning-apps/webln-reference/webln.enable

**Comment by originalix** [comment]
Thank you for your feedback. We found that when using the [WebLN Sandbox tool](https://rolznz.github.io/webln-sandbox/) recommended in the WebLN documentation, it uses a boolean value “enabled” to determine if the connection is successful, which is similar to Alby’s early implementation. 

We will fix this issue immediately.

**Comment by originalix** [comment]
Hi @bumi , we fixed this issue in https://github.com/OneKeyHQ/cross-inpage-provider/pull/132 👍
